In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("nyc_weather.csv") # data frame creation

creating df using python dictionary

In [3]:
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df= pd.DataFrame(weather_data)

In [4]:
print(df)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [5]:
rows , columns = df.shape

In [6]:
rows

6

In [7]:
columns

4

In [8]:
df.head() # first 5 records

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [9]:
df.tail()

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [10]:
df.head(2-5) #indexing or range
df[2:5]

        day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

In [11]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='str')

2 ways

In [12]:
df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: str

In [13]:
df['event']

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: str

In [14]:
type(df['event']) #series is the type in pandas

pandas.Series

In [15]:
df[['event','day']]

   event       day
0   Rain  1/1/2017
1  Sunny  1/2/2017
2   Snow  1/3/2017
3   Snow  1/4/2017
4   Rain  1/5/2017
5  Sunny  1/6/2017

operations with df

In [16]:
df['temperature'].max()

np.int64(35)

In [17]:
df['temperature'].mean()

np.float64(30.333333333333332)

In [18]:
df.describe() #print statistics

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [19]:
df['temperature'].std()

np.float64(3.8297084310253524)

In [20]:
df[df.temperature < 32]

        day  temperature  windspeed  event
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
5  1/6/2017           31          2  Sunny

In [21]:
df[df.temperature == df['temperature'].max()]  #mention column name in bracket in cases of spce in column name

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [22]:
df['temperature'] # just values

0    32
1    35
2    28
3    24
4    32
5    31
Name: temperature, dtype: int64

In [23]:
df[['day','temperature']][df.temperature == df['temperature'].max()]

        day  temperature
1  1/2/2017           35

In [24]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [25]:
df.set_index('day')

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [26]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [27]:
df.set_index('day',inplace=True)

In [29]:
df.loc['1/4/2017']

temperature      24
windspeed         7
event          Snow
Name: 1/4/2017, dtype: object

In [31]:
df.reset_index()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [32]:
df.index

Index(['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], dtype='str', name='day')

In [33]:
df.reset_index('day',inplace=True)

In [34]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [35]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [36]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [40]:
df.set_index('event',inplace=True)

In [41]:
df.index

Index(['Rain', 'Sunny', 'Snow', 'Snow', 'Rain', 'Sunny'], dtype='str', name='event')

In [43]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7