In [396]:
import pandas as pd

In [397]:
y = pd.Period('2016')
y

Period('2016', 'Y-DEC')

In [398]:
dir(y) #shows properties of period

['__add__',
 '__array_priority__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_cython__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__setstate__',
 '__setstate_cython__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__weakref__',
 '_add_offset',
 '_add_timedeltalike_scalar',
 '_dtype',
 '_freq',
 '_from_ordinal',
 '_maybe_convert_freq',
 '_ordinal',
 '_require_matching_freq',
 'asfreq',
 'day',
 'day_of_week',
 'day_of_year',
 'dayofweek',
 'dayofyear',
 'days_in_month',
 'daysinmonth',
 'end_time',
 'freq',
 'freqstr',
 'hour',
 'is_leap_year',
 'minute',
 'month',
 'now',
 'ordinal',
 'quarter',
 'qyear',
 'second',
 'start_time',
 'strftime',
 'to_timestamp',
 'week',
 'weekday',
 'weekofyear',
 'year']

In [399]:
y.start_time , y.end_time

(Timestamp('2016-01-01 00:00:00'), Timestamp('2016-12-31 23:59:59.999999'))

MONTHLY

In [400]:
m =pd.Period('2011-12',freq='M')
m

Period('2011-12', 'M')

In [401]:
m.end_time

Timestamp('2011-12-31 23:59:59.999999')

takwes you to next year

In [402]:
m +1

Period('2012-01', 'M')

DAILY

In [403]:
d = pd.Period('2016-02-28')
d

Period('2016-02-28', 'D')

leap year is considered in Period

In [404]:
d+1

Period('2016-02-29', 'D')

In [405]:
d.start_time

Timestamp('2016-02-28 00:00:00')

HOURLY

In [406]:
h = pd.Period('2016-02-28 23:00:00','h')
h

Period('2016-02-28 23:00', 'h')

In [407]:
h.start_time

Timestamp('2016-02-28 23:00:00')

In [408]:
h+pd.offsets.Hour(5)

Period('2016-02-29 04:00', 'h')

In [409]:
h.end_time

Timestamp('2016-02-28 23:59:59.999999')

In [410]:
h-6

Period('2016-02-28 17:00', 'h')

Quarterly time period

In [411]:
q = pd.Period("2017Q1")
q

Period('2017Q1', 'Q-DEC')

In [412]:
q+1

Period('2017Q2', 'Q-DEC')

In [413]:
q = pd.Period("2017Q1",freq = "Q-JAN") # end in jan
q

Period('2017Q1', 'Q-JAN')

In [414]:
q.start_time

Timestamp('2016-02-01 00:00:00')

Another way of qtl

In [415]:
q = pd.Period("2016-02-28 23:00:00","Q")
q

Period('2016Q1', 'Q-DEC')

In [416]:
q.asfreq("M",how="end")

Period('2016-03', 'M')

In [417]:
q2 = pd.Period("2018Q2")

In [418]:
q2-q

PERIODINDEX

In [419]:
idx = pd.period_range('2011','2017',freq='Q-JAN')
idx

PeriodIndex(['2011Q4', '2012Q1', '2012Q2', '2012Q3', '2012Q4', '2013Q1',
             '2013Q2', '2013Q3', '2013Q4', '2014Q1', '2014Q2', '2014Q3',
             '2014Q4', '2015Q1', '2015Q2', '2015Q3', '2015Q4', '2016Q1',
             '2016Q2', '2016Q3', '2016Q4', '2017Q1', '2017Q2', '2017Q3',
             '2017Q4'],
            dtype='period[Q-JAN]')

In [420]:
idx[0].start_time

Timestamp('2010-11-01 00:00:00')

In [421]:
idx[0].end_time

Timestamp('2011-01-31 23:59:59.999999')

In [422]:
import numpy as np
ps = pd.Series(np.random.randn(len(idx)),idx)
ps

2011Q4   -0.111027
2012Q1    1.231689
2012Q2   -0.764966
2012Q3    1.920327
2012Q4    1.429635
2013Q1   -0.666150
2013Q2    0.230249
2013Q3   -1.860422
2013Q4   -0.530633
2014Q1   -0.981864
2014Q2   -0.892349
2014Q3   -3.196675
2014Q4   -0.309708
2015Q1    0.196450
2015Q2    0.769727
2015Q3    0.373447
2015Q4   -0.164276
2016Q1    0.953931
2016Q2    0.439067
2016Q3   -0.513027
2016Q4    1.104719
2017Q1    1.389443
2017Q2    1.761354
2017Q3    1.333310
2017Q4    0.852550
Freq: Q-JAN, dtype: float64

In [423]:
ps.index

PeriodIndex(['2011Q4', '2012Q1', '2012Q2', '2012Q3', '2012Q4', '2013Q1',
             '2013Q2', '2013Q3', '2013Q4', '2014Q1', '2014Q2', '2014Q3',
             '2014Q4', '2015Q1', '2015Q2', '2015Q3', '2015Q4', '2016Q1',
             '2016Q2', '2016Q3', '2016Q4', '2017Q1', '2017Q2', '2017Q3',
             '2017Q4'],
            dtype='period[Q-JAN]')

Retrieving values

In [424]:
ps['2011':'2013']

2011Q4   -0.111027
2012Q1    1.231689
2012Q2   -0.764966
2012Q3    1.920327
2012Q4    1.429635
2013Q1   -0.666150
2013Q2    0.230249
2013Q3   -1.860422
2013Q4   -0.530633
2014Q1   -0.981864
2014Q2   -0.892349
2014Q3   -3.196675
2014Q4   -0.309708
Freq: Q-JAN, dtype: float64

In [425]:
df = pd.read_csv("wmt.csv")
df

  Line Item  2017Q1  2017Q2  2017Q3  2017Q4  2018Q1
0   Revenue  115904  120854  118179  130936  117542
1  Expenses   86544   89485   87484   97743   87688
2    Profit   29360   31369   30695   33193   29854

In [426]:
df.set_index('Line Item',inplace=True)

In [427]:
df

           2017Q1  2017Q2  2017Q3  2017Q4  2018Q1
Line Item
Revenue    115904  120854  118179  130936  117542
Expenses    86544   89485   87484   97743   87688
Profit      29360   31369   30695   33193   29854

In [428]:
df=df.T  #transpose table
df

Line Item  Revenue  Expenses  Profit
2017Q1      115904     86544   29360
2017Q2      120854     89485   31369
2017Q3      118179     87484   30695
2017Q4      130936     97743   33193
2018Q1      117542     87688   29854

In [431]:
df.index

PeriodIndex(['2017Q1', '2017Q2', '2017Q3', '2017Q4', '2018Q1'], dtype='period[Q-JAN]')

In [436]:
df['start_date']= df.index.map(lambda x:x.start_time)
df['end_date']=df.index.map(lambda x:x.end_time)

In [437]:
df

Line Item  Revenue  Expenses  Profit start_date                   end_date
2017Q1      115904     86544   29360 2016-02-01 2016-04-30 23:59:59.999999
2017Q2      120854     89485   31369 2016-05-01 2016-07-31 23:59:59.999999
2017Q3      118179     87484   30695 2016-08-01 2016-10-31 23:59:59.999999
2017Q4      130936     97743   33193 2016-11-01 2017-01-31 23:59:59.999999
2018Q1      117542     87688   29854 2017-02-01 2017-04-30 23:59:59.999999