In [56]:
import pandas as pd

In [57]:
df = pd.read_csv("fb.csv",parse_dates=["Date"],index_col="Date")
df

/var/folders/5f/pxqbh0g96sg4ws9dv4jhv51c0000gn/T/ipykernel_3790/3036640011.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("fb.csv",parse_dates=["Date"],index_col="Date")

             Price
Date
2017-08-15  171.00
2017-08-16  170.00
2017-08-17  166.91
2017-08-18  167.41
2017-08-21  167.78
2017-08-22  169.64
2017-08-23  168.71
2017-08-24  167.74
2017-08-25  166.32
2017-08-28  167.24

shifting prices

In [58]:
df.shift(+1)

             Price
Date
2017-08-15     NaN
2017-08-16  171.00
2017-08-17  170.00
2017-08-18  166.91
2017-08-21  167.41
2017-08-22  167.78
2017-08-23  169.64
2017-08-24  168.71
2017-08-25  167.74
2017-08-28  166.32

In [59]:
df['prev_day']=df.shift(-1)
df

             Price  prev_day
Date
2017-08-15  171.00    170.00
2017-08-16  170.00    166.91
2017-08-17  166.91    167.41
2017-08-18  167.41    167.78
2017-08-21  167.78    169.64
2017-08-22  169.64    168.71
2017-08-23  168.71    167.74
2017-08-24  167.74    166.32
2017-08-25  166.32    167.24
2017-08-28  167.24       NaN

In [60]:
df['price_change']= df['Price'] - df['prev_day']
df

             Price  prev_day  price_change
Date
2017-08-15  171.00    170.00          1.00
2017-08-16  170.00    166.91          3.09
2017-08-17  166.91    167.41         -0.50
2017-08-18  167.41    167.78         -0.37
2017-08-21  167.78    169.64         -1.86
2017-08-22  169.64    168.71          0.93
2017-08-23  168.71    167.74          0.97
2017-08-24  167.74    166.32          1.42
2017-08-25  166.32    167.24         -0.92
2017-08-28  167.24       NaN           NaN

In [61]:
df['5 day return'] =  (df['Price'] - df['Price'].shift(5))*100/df['Price'].shift(5)
df

             Price  prev_day  price_change  5 day return
Date
2017-08-15  171.00    170.00          1.00           NaN
2017-08-16  170.00    166.91          3.09           NaN
2017-08-17  166.91    167.41         -0.50           NaN
2017-08-18  167.41    167.78         -0.37           NaN
2017-08-21  167.78    169.64         -1.86           NaN
2017-08-22  169.64    168.71          0.93     -0.795322
2017-08-23  168.71    167.74          0.97     -0.758824
2017-08-24  167.74    166.32          1.42      0.497274
2017-08-25  166.32    167.24         -0.92     -0.651096
2017-08-28  167.24       NaN           NaN     -0.321850

changing date

In [62]:
df = df[['Price']]
df

             Price
Date
2017-08-15  171.00
2017-08-16  170.00
2017-08-17  166.91
2017-08-18  167.41
2017-08-21  167.78
2017-08-22  169.64
2017-08-23  168.71
2017-08-24  167.74
2017-08-25  166.32
2017-08-28  167.24

In [63]:
df.index = pd.date_range(start="2017-08-15",periods=10,freq="B")
df.index

DatetimeIndex(['2017-08-15', '2017-08-16', '2017-08-17', '2017-08-18',
               '2017-08-21', '2017-08-22', '2017-08-23', '2017-08-24',
               '2017-08-25', '2017-08-28'],
              dtype='datetime64[us]', freq='B')

adjust the date

In [67]:
df.shift(periods=1, freq='D')

             Price
2017-08-16  171.00
2017-08-17  170.00
2017-08-18  166.91
2017-08-19  167.41
2017-08-22  167.78
2017-08-23  169.64
2017-08-24  168.71
2017-08-25  167.74
2017-08-26  166.32
2017-08-29  167.24