In [67]:
import pandas as pd

In [68]:
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [69]:
df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'],axis=1,inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [70]:
target = df.Survived
inputs = df.drop(df[['Survived']], axis=1)

In [71]:
dummies  =pd.get_dummies(inputs.Sex,dtype=int)
dummies.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [72]:
inputs = pd.concat([inputs,dummies], axis=1)

In [73]:
inputs

     Pclass     Sex   Age     Fare  female  male
0         3    male  22.0   7.2500       0     1
1         1  female  38.0  71.2833       1     0
2         3  female  26.0   7.9250       1     0
3         1  female  35.0  53.1000       1     0
4         3    male  35.0   8.0500       0     1
..      ...     ...   ...      ...     ...   ...
886       2    male  27.0  13.0000       0     1
887       1  female  19.0  30.0000       1     0
888       3  female   NaN  23.4500       1     0
889       1    male  26.0  30.0000       0     1
890       3    male  32.0   7.7500       0     1

[891 rows x 6 columns]

In [74]:
inputs = inputs.drop('Sex',axis=1)
inputs.head()

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [75]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='str')

In [76]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [77]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(8)

   Pclass        Age     Fare  female  male
0       3  22.000000   7.2500       0     1
1       1  38.000000  71.2833       1     0
2       3  26.000000   7.9250       1     0
3       1  35.000000  53.1000       1     0
4       3  35.000000   8.0500       0     1
5       3  29.699118   8.4583       0     1
6       1  54.000000  51.8625       0     1
7       3   2.000000  21.0750       0     1

In [92]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(inputs,target,test_size=0.2)

In [83]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [93]:
model.fit(X_train,y_train)

GaussianNB()

In [94]:
model.score(X_test,y_test)

0.8435754189944135

In [95]:
X_test[:10]

     Pclass        Age     Fare  female  male
53        2  29.000000  26.0000       1     0
747       2  30.000000  13.0000       1     0
107       3  29.699118   7.7750       0     1
173       3  21.000000   7.9250       0     1
562       2  28.000000  13.5000       0     1
179       3  36.000000   0.0000       0     1
230       1  35.000000  83.4750       1     0
743       3  24.000000  16.1000       0     1
515       1  47.000000  34.0208       0     1
601       3  29.699118   7.8958       0     1

In [96]:
model.predict(X_test[:10])

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 0])

In [97]:
model.predict_proba(X_test[:10])

array([[0.05349063, 0.94650937],
       [0.05603022, 0.94396978],
       [0.98911966, 0.01088034],
       [0.98788214, 0.01211786],
       [0.97518861, 0.02481139],
       [0.98826542, 0.01173458],
       [0.00294414, 0.99705586],
       [0.98868219, 0.01131781],
       [0.87257311, 0.12742689],
       [0.98912543, 0.01087457]])