In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("weather_data.csv",parse_dates=['day'])
type(df.day[0])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [4]:
df.set_index('day',inplace=True) # inplace is to apply instead of copying
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

fillna with one value for all

In [5]:
new_df = df.fillna(0)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          0.0        9.0   Sunny
2017-01-05         28.0        0.0    Snow
2017-01-06          0.0        7.0       0
2017-01-07         32.0        0.0    Rain
2017-01-08          0.0        0.0   Sunny
2017-01-09          0.0        0.0       0
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

Fill na using column names and dict

In [7]:
new_df = df.fillna({
        'temperature': 0,
        'windspeed': 0,
        'event': 'No Event'
    })
new_df

            temperature  windspeed     event
day
2017-01-01         32.0        6.0      Rain
2017-01-04          0.0        9.0     Sunny
2017-01-05         28.0        0.0      Snow
2017-01-06          0.0        7.0  No Event
2017-01-07         32.0        0.0      Rain
2017-01-08          0.0        0.0     Sunny
2017-01-09          0.0        0.0  No Event
2017-01-10         34.0        8.0    Cloudy
2017-01-11         40.0       12.0     Sunny

FFILL

In [8]:
new_df= df.ffill()

In [9]:
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        7.0   Sunny
2017-01-09         32.0        7.0   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [11]:
new_df=df.bfill()
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.0    Rain
2017-01-08         34.0        8.0   Sunny
2017-01-09         34.0        8.0  Cloudy
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

Use of axis

In [12]:
new_df = df.bfill(axis='columns')
new_df

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04         9.0       9.0   Sunny
2017-01-05        28.0      Snow    Snow
2017-01-06         7.0       7.0     NaN
2017-01-07        32.0      Rain    Rain
2017-01-08       Sunny     Sunny   Sunny
2017-01-09         NaN       NaN     NaN
2017-01-10        34.0       8.0  Cloudy
2017-01-11        40.0      12.0   Sunny

limit parameter

In [13]:
new_df = df.ffill(limit=1)

In [14]:
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        NaN   Sunny
2017-01-09          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

interpolate

In [42]:
num = ['temperature','windspeed']
df[num]=df[num].interpolate(method='linear') # parameters for accuracy

In [43]:
df['event'] = df['event'].ffill(limit=1)

In [44]:
df

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    30.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00    Snow
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75   Sunny
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

dropna

In [45]:
new_df = df.dropna()
new_df

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    30.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00    Snow
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75   Sunny
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

In [46]:
new_df = df.dropna(how='all')
new_df

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    30.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00    Snow
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75   Sunny
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

In [47]:
new_df = df.dropna(thresh=1)
new_df

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    30.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00    Snow
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75   Sunny
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

Inserting Missing Dates

In [48]:
dt = pd.date_range("01-01-2017","01-11-2017")
idx = pd.DatetimeIndex(dt)
df.reindex(idx)

            temperature  windspeed   event
2017-01-01    32.000000       6.00    Rain
2017-01-02          NaN        NaN     NaN
2017-01-03          NaN        NaN     NaN
2017-01-04    30.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00    Snow
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75   Sunny
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny