In [88]:
import pandas as pd
import numpy as np

In [89]:
df = pd.read_csv("weather_data_replace.csv")
df

        day temperature windspeed     event
0  1/1/2017        32 F     6 mph      Rain
1  1/2/2017      -99999     7 mph     Sunny
2  1/3/2017          28    -99999      Snow
3  1/4/2017      -99999         7  no event
4  1/5/2017        32 C    -88888      Rain
5  1/6/2017          31         2     Sunny
6  1/6/2017          34         5  no event

In [90]:
new_df=df.replace(-99999,np.nan)
new_df

        day temperature windspeed     event
0  1/1/2017        32 F     6 mph      Rain
1  1/2/2017      -99999     7 mph     Sunny
2  1/3/2017          28    -99999      Snow
3  1/4/2017      -99999         7  no event
4  1/5/2017        32 C    -88888      Rain
5  1/6/2017          31         2     Sunny
6  1/6/2017          34         5  no event

multiple values use list

In [91]:
new_df = df.replace([-99999,-88888,0,"0"],np.nan)
new_df

        day temperature windspeed     event
0  1/1/2017        32 F     6 mph      Rain
1  1/2/2017      -99999     7 mph     Sunny
2  1/3/2017          28    -99999      Snow
3  1/4/2017      -99999         7  no event
4  1/5/2017        32 C    -88888      Rain
5  1/6/2017          31         2     Sunny
6  1/6/2017          34         5  no event

use of dict

In [92]:
new_df = df.replace({
    'temperature':-99999,
    'windspeed':[-99999,-88888],
    'event':'0'}
    ,np.nan)

In [93]:
new_df

        day temperature windspeed     event
0  1/1/2017        32 F     6 mph      Rain
1  1/2/2017      -99999     7 mph     Sunny
2  1/3/2017          28    -99999      Snow
3  1/4/2017      -99999         7  no event
4  1/5/2017        32 C    -88888      Rain
5  1/6/2017          31         2     Sunny
6  1/6/2017          34         5  no event

mapping with dictionary

In [94]:
new_df = df.replace({
    -99999:np.nan,
    "no event":"Sunny"
})

In [95]:
new_df

        day temperature windspeed  event
0  1/1/2017        32 F     6 mph   Rain
1  1/2/2017      -99999     7 mph  Sunny
2  1/3/2017          28    -99999   Snow
3  1/4/2017      -99999         7  Sunny
4  1/5/2017        32 C    -88888   Rain
5  1/6/2017          31         2  Sunny
6  1/6/2017          34         5  Sunny

regex- regular expression

In [96]:
new_df = df.replace('[A-za-z]','',regex=True)
new_df

        day temperature windspeed event
0  1/1/2017         32         6
1  1/2/2017      -99999        7
2  1/3/2017          28    -99999
3  1/4/2017      -99999         7
4  1/5/2017         32     -88888
5  1/6/2017          31         2
6  1/6/2017          34         5

this removed all characters

In [97]:
new_df = df.replace({
    'temperature':['A-Za-z'],
    'windspeed':['A-Za-z']}
    ,'',regex=True
)
new_df

        day temperature windspeed     event
0  1/1/2017        32 F     6 mph      Rain
1  1/2/2017      -99999     7 mph     Sunny
2  1/3/2017          28    -99999      Snow
3  1/4/2017      -99999         7  no event
4  1/5/2017        32 C    -88888      Rain
5  1/6/2017          31         2     Sunny
6  1/6/2017          34         5  no event

Replacing list with another list

In [98]:
df = pd.DataFrame({
    'score': ['exceptional','average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [99]:
df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4])

  score  student
0     4      rob
1     2     maya
2     3  parthiv
3     1      tom
4     2   julian
5     4    erica