In [2]:
import pandas as pd

In [3]:
weather_india = pd.DataFrame({
    'city':['mumbai','delhi','bangalore'],
    'temperature':[32,45,30],
    'humidity':[80,60,78]
})

In [4]:
weather_india

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78

In [5]:
weather_usa = pd.DataFrame({
    'city':['new york','chicago','orlando'],
    'temperature':[21,14,35],
    'humidity':[68,65,75]
})

In [6]:
weather_usa

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

merge two dataframes

In [7]:
df = pd.concat([weather_india,weather_usa],ignore_index=True) #two avoid og index

In [8]:
df

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78
3   new york           21        68
4    chicago           14        65
5    orlando           35        75

passing keys

In [9]:
df = pd.concat([weather_india,weather_usa],keys=['india','usa'])
df

              city  temperature  humidity
india 0     mumbai           32        80
      1      delhi           45        60
      2  bangalore           30        78
usa   0   new york           21        68
      1    chicago           14        65
      2    orlando           35        75

In [10]:
df.loc['usa']

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [13]:
temp_data=pd.DataFrame({
    'city':['new york','chicago','orlando'],
    'temperature':[21,14,35]
})
temp_data

       city  temperature
0  new york           21
1   chicago           14
2   orlando           35

In [23]:
windspeed=pd.DataFrame({
    'city':['chicago','new york'],
    'temperature':[7,12]
},index=[1,0]) #for having proper order
windspeed

       city  temperature
1   chicago            7
0  new york           12

concat as rows

In [25]:
df=pd.concat([temp_data,windspeed],axis=1) #rows
df

       city  temperature      city  temperature
0  new york           21  new york         12.0
1   chicago           14   chicago          7.0
2   orlando           35       NaN          NaN

In [26]:
temp_data

       city  temperature
0  new york           21
1   chicago           14
2   orlando           35

join dataframe with series

In [30]:
s = pd.Series(["humid","dry","rain"],name="event")

In [31]:
df = pd.concat([temp_data,s],axis=1)
df

       city  temperature  event
0  new york           21  humid
1   chicago           14    dry
2   orlando           35   rain