In [11]:
import pandas as pd

In [17]:
df1=pd.DataFrame({
    'city':['new york','chicago','orlando','baltimore'],
    'temperature':[21,14,35,32]
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           32

In [18]:
df2=pd.DataFrame({
    'city':['new york','chicago','san fransisco'],
    'humidity':[65,68,71]
})

inner join

In [26]:
df = pd.merge(df1,df2,on='city')
df

       city  temperature  humidity
0  new york           21        65
1   chicago           14        68

outer join

In [27]:
df = pd.merge(df1,df2,on='city',how='outer')
df

            city  temperature  humidity
0      baltimore         32.0       NaN
1        chicago         14.0      68.0
2       new york         21.0      65.0
3        orlando         35.0       NaN
4  san fransisco          NaN      71.0

left join

In [28]:
df = pd.merge(df1,df2,on='city',how='left')
df

        city  temperature  humidity
0   new york           21      65.0
1    chicago           14      68.0
2    orlando           35       NaN
3  baltimore           32       NaN

right join

In [29]:
df = pd.merge(df1, df2, on='city', how='right')
df

            city  temperature  humidity
0       new york         21.0        65
1        chicago         14.0        68
2  san fransisco          NaN        71

In [30]:
df = pd.merge(df1,df2,on='city',how='outer',indicator=True)
df

            city  temperature  humidity      _merge
0      baltimore         32.0       NaN   left_only
1        chicago         14.0      68.0        both
2       new york         21.0      65.0        both
3        orlando         35.0       NaN   left_only
4  san fransisco          NaN      71.0  right_only

suffixes

In [31]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35,38],
    "humidity": [65,68,71, 75]
})
df1

        city  temperature  humidity
0   new york           21        65
1    chicago           14        68
2    orlando           35        71
3  baltimore           38        75

In [32]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "temperature": [21,14,35],
    "humidity": [65,68,71]
})
df2

        city  temperature  humidity
0    chicago           21        65
1   new york           14        68
2  san diego           35        71

In [33]:
df3= pd.merge(df1,df2,on="city",how="outer", suffixes=('_first','_second'))
df3

,city,temperature_first,humidity_first,temperature_second,humidity_second
0,baltimore,38.0,75.0,NaN,NaN
1,chicago,14.0,68.0,21.0,65.0
2,new york,21.0,65.0,14.0,68.0
3,orlando,35.0,71.0,NaN,NaN
4,san diego,NaN,NaN,35.0,71.0