In [22]:
import pandas as pd

using csv file

In [23]:
df= pd.read_csv("nyc_weather.csv")

using excel

In [24]:
df= pd.read_excel("weather_data.xlsx","Sheet1")

In [25]:
df

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [26]:
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df=pd.DataFrame()

In [27]:
weather_data = [
    ('1/1/2017',32,6,'Rain'),
    ('1/2/2017',35,7,'Sunny'),
    ('1/3/2017',28,2,'Snow')
]
df = pd.DataFrame(data=weather_data, columns=['day','temperature','windspeed','event'])
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [28]:
weather_data = [
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},

]
df= pd.DataFrame(weather_data, columns=['day','temperature','windspeed','event'])
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [29]:
df = pd.read_csv("stock_data.csv",skiprows=1) #or header=1
df

  GOOGL          27.82   87   845     larry page
0   WMT           4.61  484    65           n.a.
1  MSFT             -1   85    64     bill gates
2  RIL   not available   50  1023  mukesh ambani
3  TATA            5.6   -1  n.a.     ratan tata

In [30]:
df = pd.read_csv("stock_data.csv",header=None,names=["ticker","esp","revenue","people","price"])
df

    ticker            esp  revenue people          price
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4     RIL   not available       50   1023  mukesh ambani
5     TATA            5.6       -1   n.a.     ratan tata

read n number of rows

In [31]:
df = pd.read_csv("stock_data.csv",nrows=3)
df

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.
2    MSFT  -1.00       85     64  bill gates

cleaning up messy values with nan

In [33]:
df = pd.read_csv("stock_data.csv",na_values=["not available","n.a."])
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3    RIL     NaN       50  1023.0  mukesh ambani
4    TATA   5.60       -1     NaN     ratan tata

for applying to selected cells

In [38]:
df = pd.read_csv("stock_data.csv",na_values={
    'eps':["not available","n.a."],
    'revenue':["not available","n.a.",-1],
    'price':["not available","n.a."]})
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0           n.a.
2    MSFT  -1.00     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

write in csv

In [51]:
df.to_csv('new_data.csv',index=False) #to remove extra indexing

just exporting required columns

In [50]:
df.to_csv('new_data.csv',columns=['tickers','eps'])

skip header

In [53]:
df.to_csv('new_data.csv',header=False)

for excel

In [58]:
df =pd.read_excel("stock_data.xlsx","Sheet1")
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

adding value using converter

In [62]:
def converting_cell(cell):
    if cell == 'n.a.':
        return "sam walton"
    return cell

def eps_cell(cell):
    if cell == 'not available':
        return None
    return cell

In [63]:
df =pd.read_excel("stock_data.xlsx","Sheet1",converters={
    'people':converting_cell,
    'eps':eps_cell
})
df

  tickers    eps  revenue price         people
0   GOOGL  27.82       87   845     larry page
1     WMT   4.61      484    65     sam walton
2    MSFT  -1.00       85    64     bill gates
3    RIL     NaN       50  1023  mukesh ambani
4    TATA   5.60       -1  n.a.     ratan tata

write in excel

In [72]:
df.to_excel('new_data.xlsx',sheet_name="stocks")
df

  tickers    eps  revenue price         people
0   GOOGL  27.82       87   845     larry page
1     WMT   4.61      484    65     sam walton
2    MSFT  -1.00       85    64     bill gates
3    RIL     NaN       50  1023  mukesh ambani
4    TATA   5.60       -1  n.a.     ratan tata

In [75]:
df.to_excel('new_data.xlsx',sheet_name="stocks",startrow=1,startcol=2,index=False)
df

  tickers    eps  revenue price         people
0   GOOGL  27.82       87   845     larry page
1     WMT   4.61      484    65     sam walton
2    MSFT  -1.00       85    64     bill gates
3    RIL     NaN       50  1023  mukesh ambani
4    TATA   5.60       -1  n.a.     ratan tata

Write two dataframes to two separate sheets in excel

In [76]:
df_stocks = pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64 ],
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})

df_weather =  pd.DataFrame({
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'event': ['Rain', 'Sunny', 'Snow']
})

In [78]:
with pd.ExcelWriter('stocks_weather.xlsx') as writer:
    df_stocks.to_excel(writer, sheet_name="stocks")
    df_weather.to_excel(writer, sheet_name="weather")